version: '3.8'

services:
  # --- Your FastAPI Python Application Workspace ---
  web_api:
    build: .
    container_name: taskpulse_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/backend  # Mounts source files for live-reload updates during programming
    networks:
      - taskpulse_network

networks:
  taskpulse_network:
    driver: bridge
